

// This file was automatically generated by Coco/R; don't modify it.
#if !defined(Ob_COCO_PARSER_H__)
#define Ob_COCO_PARSER_H__

#include <QStack>
#include <Oberon/ObSynTree.h>


#include "ObLexer.h"

namespace Ob {



class Parser {
private:
	enum {
		_EOF=0,
		_T_Literals_=1,
		_T_Hash=2,
		_T_Dlr=3,
		_T_Amp=4,
		_T_Lpar=5,
		_T_Latt=6,
		_T_Rpar=7,
		_T_Star=8,
		_T_Ratt=9,
		_T_Plus=10,
		_T_Comma=11,
		_T_Minus=12,
		_T_Dot=13,
		_T_2Dot=14,
		_T_Slash=15,
		_T_2Slash=16,
		_T_Colon=17,
		_T_ColonEq=18,
		_T_Semi=19,
		_T_Lt=20,
		_T_Leq=21,
		_T_Eq=22,
		_T_Gt=23,
		_T_Geq=24,
		_T_Lbrack=25,
		_T_Rbrack=26,
		_T_Hat=27,
		_T_Lbrace=28,
		_T_Bar=29,
		_T_Rbrace=30,
		_T_Tilde=31,
		_T_Keywords_=32,
		_T_ABSTRACT=33,
		_T_ARRAY=34,
		_T_BEGIN=35,
		_T_BY=36,
		_T_CARRAY=37,
		_T_CASE=38,
		_T_CLOSE=39,
		_T_CONST=40,
		_T_CPOINTER=41,
		_T_CSTRUCT=42,
		_T_CUNION=43,
		_T_DEFINITION=44,
		_T_DIV=45,
		_T_DO=46,
		_T_ELSE=47,
		_T_ELSIF=48,
		_T_EMPTY=49,
		_T_END=50,
		_T_EXIT=51,
		_T_EXTENSIBLE=52,
		_T_FALSE=53,
		_T_FOR=54,
		_T_IF=55,
		_T_IMPORT=56,
		_T_IN=57,
		_T_IS=58,
		_T_LIMITED=59,
		_T_LOOP=60,
		_T_MOD=61,
		_T_MODULE=62,
		_T_NIL=63,
		_T_OF=64,
		_T_OR=65,
		_T_OUT=66,
		_T_POINTER=67,
		_T_PROC=68,
		_T_PROCEDURE=69,
		_T_RECORD=70,
		_T_REPEAT=71,
		_T_RETURN=72,
		_T_THEN=73,
		_T_TO=74,
		_T_TRUE=75,
		_T_TYPE=76,
		_T_UNSAFE=77,
		_T_UNTIL=78,
		_T_VAR=79,
		_T_WHILE=80,
		_T_WITH=81,
		_T_Specials_=82,
		_T_ident=83,
		_T_integer=84,
		_T_real=85,
		_T_string=86,
		_T_hexchar=87,
		_T_hexstring=88,
		_T_Comment=89,
		_T_Eof=90,
		_T_MaxToken_=91
	};
	int maxT;

	int errDist;
	int minErrDist;

	void SynErr(int n, const char* ctx = 0);
	void Get();
	void Expect(int n, const char* ctx = 0);
	bool StartOf(int s);
	void ExpectWeak(int n, int follow);
	bool WeakSeparator(int n, int syFol, int repFol);
    void SynErr(const QString& sourcePath, int line, int col, int n, Ob::Errors* err, const char* ctx, const QString& = QString() );

public:
	Ob::Lexer *scanner;
	Ob::Errors  *errors;

	Ob::Token d_cur;
	Ob::Token d_next;
	QList<Ob::Token> d_comments;
	struct TokDummy
	{
		int kind;
	};
	TokDummy d_dummy;
	TokDummy *la;			// lookahead token
	
	int peek( quint8 la = 1 );

    void RunParser();

    
Ob::SynTree d_root;
	QStack<Ob::SynTree*> d_stack;
	void addTerminal() {
		if( d_cur.d_type != Ob::Tok_Semi && d_cur.d_type != Ob::Tok_Comma && d_cur.d_type != Ob::Tok_Dot && d_cur.d_type != Ob::Tok_Colon ){
			Ob::SynTree* n = new Ob::SynTree( d_cur ); d_stack.top()->d_children.append(n);
		}
	}



	Parser(Ob::Lexer *scanner,Ob::Errors*);
	~Parser();
	void SemErr(const char* msg);

	void Oberon();
	void module();
	void definition();
	void number();
	void qualident();
	void identdef();
	void ConstDeclaration();
	void ConstExpression();
	void expression();
	void TypeDeclaration();
	void type();
	void NamedType();
	void ArrayType();
	void RecordType();
	void PointerType();
	void ProcedureType();
	void SysFlag();
	void LengthList();
	void length();
	void SysString();
	void BaseType();
	void FieldListSequence();
	void FieldList();
	void IdentList();
	void FormalParameters();
	void VariableDeclaration();
	void designator();
	void selector();
	void ExpList();
	void SimpleExpression();
	void relation();
	void term();
	void AddOperator();
	void factor();
	void MulOperator();
	void literal();
	void set();
	void variableOrFunctionCall();
	void element();
	void statement();
	void assignmentOrProcedureCall();
	void IfStatement();
	void CaseStatement();
	void WithStatement();
	void LoopStatement();
	void ExitStatement();
	void ReturnStatement();
	void WhileStatement();
	void RepeatStatement();
	void ForStatement();
	void StatementSequence();
	void ElsifStatement();
	void ElseStatement();
	void Case();
	void CaseLabelList();
	void LabelRange();
	void label();
	void ElsifStatement2();
	void Guard();
	void ProcedureDeclaration();
	void Receiver();
	void MethAttributes();
	void ProcedureHeading();
	void ProcedureBody();
	void DeclarationSequence();
	void DeclarationSequence2();
	void FPSection();
	void FormalType();
	void ImportList();
	void import();

	void Parse();

}; // end Parser

} // namespace


#endif

