name: Build ObxIDE Windows x64

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Create build directory
      run: mkdir build
      shell: cmd
      
    - name: Checkout Oberon repository
      uses: actions/checkout@v4
      with:
        path: build/Obx
        
    - name: Download BUSY
      run: |
        cd build
        curl -L https://github.com/rochus-keller/BUSY/archive/refs/heads/main.zip -o busy.zip
        tar -xf busy.zip
        move BUSY-main BUSY
      shell: cmd
      
    - name: Build BUSY
      run: |
        cd build/BUSY
        cl -O2 -MD -Fe:lua.exe *.c
      shell: cmd
      
    - name: Download dependencies
      run: |
        cd build
        curl -L https://github.com/rochus-keller/PeLib/archive/refs/heads/OBX.zip -o pelib.zip
        tar -xf pelib.zip
        move PeLib-OBX PeLib
        
        curl -L https://github.com/rochus-keller/MonoTools/archive/refs/heads/master.zip -o monotools.zip
        tar -xf monotools.zip
        move MonoTools-master MonoTools
        
        curl -L https://github.com/rochus-keller/GuiTools/archive/refs/heads/master.zip -o guitools.zip
        tar -xf guitools.zip
        move GuiTools-master GuiTools
        
        curl -L https://github.com/rochus-keller/LeanQt/archive/refs/heads/main.zip -o leanqt.zip
        tar -xf leanqt.zip
        move LeanQt-main LeanQt
      shell: cmd
      
    - name: Verify structure
      run: |
        cd build
        echo "Build directory contents:"
        dir
        echo "Checking for BUSY config file:"
        if exist "Obx\BUSY" (
          echo "✓ BUSY config file found"
        ) else (
          echo "✗ BUSY config file missing"
        )
      shell: cmd
      
    - name: Build ObxIDE
      run: |
        cd build/BUSY
        lua.exe build.lua ../Obx -T ide
      shell: cmd
      
    - name: Package artifacts
      run: |
        cd build/BUSY/output
        mkdir ..\..\..\artifacts
        if exist "ObxIDE.exe" copy ObxIDE.exe ..\..\..\artifacts\ObxIDE_win64.exe
        if exist "mono" xcopy mono ..\..\..\artifacts\mono\ /E /I
      shell: cmd
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ObxIDE_win64
        path: artifacts/
        retention-days: 30

