name: Build ObxIDE

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-22.04
            arch: x64
            cc: gcc
            output_suffix: linux_x64
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Oberon repository
      uses: actions/checkout@v4
      with:
        path: Oberon
        
    - name: Setup build environment (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libxcb1-dev libx11-dev
        if [ "${{ matrix.arch }}" = "x86" ]; then
          sudo apt-get install -y gcc-multilib g++-multilib
        fi
        
    - name: Setup build environment (Windows)
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup build environment (macOS)
      if: runner.os == 'macOS'
      run: |
        echo "macOS build environment ready"
        
    - name: Download and build BUSY
      run: |
        # Download BUSY
        if [ "${{ runner.os }}" = "Windows" ]; then
          curl -L https://github.com/rochus-keller/BUSY/archive/refs/heads/main.zip -o busy.zip
          unzip busy.zip
          mv BUSY-main BUSY
        else
          wget https://github.com/rochus-keller/BUSY/archive/refs/heads/main.tar.gz -O busy.tar.gz
          tar -xzf busy.tar.gz
          mv BUSY-main BUSY
        fi
        
        # Build BUSY
        cd BUSY
        if [ "${{ runner.os }}" = "Windows" ]; then
          cl /O2 /MD /Fe:lua.exe *.c
        else
          if [ "${{ matrix.arch }}" = "x86" ] && [ "${{ runner.os }}" = "Linux" ]; then
            gcc -m32 *.c -O2 -lm -o lua
          else
            cc *.c -O2 -lm -o lua
          fi
        fi
      shell: bash
      
    - name: Download required dependencies
      run: |
        # Download PeLib
        if [ "${{ runner.os }}" = "Windows" ]; then
          curl -L https://github.com/rochus-keller/PeLib/archive/refs/heads/OBX.zip -o pelib.zip
          unzip pelib.zip
          mv PeLib-OBX PeLib
        else
          wget https://github.com/rochus-keller/PeLib/archive/refs/heads/OBX.tar.gz -O pelib.tar.gz
          tar -xzf pelib.tar.gz
          mv PeLib-OBX PeLib
        fi
        
        # Download MonoTools
        if [ "${{ runner.os }}" = "Windows" ]; then
          curl -L https://github.com/rochus-keller/MonoTools/archive/refs/heads/master.zip -o monotools.zip
          unzip monotools.zip
          mv MonoTools-master MonoTools
        else
          wget https://github.com/rochus-keller/MonoTools/archive/refs/heads/master.tar.gz -O monotools.tar.gz
          tar -xzf monotools.tar.gz
          mv MonoTools-master MonoTools
        fi
        
        # Download GuiTools
        if [ "${{ runner.os }}" = "Windows" ]; then
          curl -L https://github.com/rochus-keller/GuiTools/archive/refs/heads/master.zip -o guitools.zip
          unzip guitools.zip
          mv GuiTools-master GuiTools
        else
          wget https://github.com/rochus-keller/GuiTools/archive/refs/heads/master.tar.gz -O guitools.tar.gz
          tar -xzf guitools.tar.gz
          mv GuiTools-master GuiTools
        fi
        
        # Download LeanQt
        if [ "${{ runner.os }}" = "Windows" ]; then
          curl -L https://github.com/rochus-keller/LeanQt/archive/refs/heads/main.zip -o leanqt.zip
          unzip leanqt.zip
          mv LeanQt-main LeanQt
        else
          wget https://github.com/rochus-keller/LeanQt/archive/refs/heads/main.tar.gz -O leanqt.tar.gz
          tar -xzf leanqt.tar.gz
          mv LeanQt-main LeanQt
        fi
      shell: bash
      
    - name: Build ObxIDE
      run: |
        cd BUSY
        
        # Build the IDE - pointing to the Oberon directory
        if [ "${{ runner.os }}" = "Windows" ]; then
          ./lua.exe build.lua ../Oberon -T ide
        else
          ./lua build.lua ../Oberon -T ide
        fi
      shell: bash
      
    - name: Package artifacts
      run: |
        cd BUSY/output
        
        # Create package directory
        mkdir -p ../../artifacts
        
        # Copy built executable
        if [ "${{ runner.os }}" = "Windows" ]; then
          if [ -f ObxIDE.exe ]; then
            cp ObxIDE.exe ../../artifacts/ObxIDE_${{ matrix.output_suffix }}.exe
          fi
        else
          if [ -f ObxIDE ]; then
            cp ObxIDE ../../artifacts/ObxIDE_${{ matrix.output_suffix }}
          fi
        fi
        
        # Copy any additional required files
        if [ -d mono ]; then
          cp -r mono ../../artifacts/
        fi
      shell: bash
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ObxIDE_${{ matrix.output_suffix }}
        path: artifacts/
        retention-days: 30

