name: Build ObxIDE (Windows)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            arch: x64
            output_suffix: win64
          - os: windows-2022
            arch: x86
            output_suffix: win32

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Setup Visual Studio environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch == 'x86' && 'x86' || 'x64' }}
        
    - name: Checkout Oberon repository
      uses: actions/checkout@v4
      # Don't use path parameter - checkout directly to workspace root
        
    - name: Download and build BUSY
      run: |
        Invoke-WebRequest -Uri "https://github.com/rochus-keller/BUSY/archive/refs/heads/main.zip" -OutFile "busy.zip"
        Expand-Archive -Path "busy.zip" -DestinationPath "."
        Rename-Item -Path "BUSY-main" -NewName "BUSY"
        
        Set-Location BUSY
        cl /O2 /MD /Fe:lua.exe *.c
      shell: powershell
      
    - name: Download required dependencies
      run: |
        # Download PeLib
        Invoke-WebRequest -Uri "https://github.com/rochus-keller/PeLib/archive/refs/heads/OBX.zip" -OutFile "pelib.zip"
        Expand-Archive -Path "pelib.zip" -DestinationPath "."
        Rename-Item -Path "PeLib-OBX" -NewName "PeLib"
        
        # Download MonoTools
        Invoke-WebRequest -Uri "https://github.com/rochus-keller/MonoTools/archive/refs/heads/master.zip" -OutFile "monotools.zip"
        Expand-Archive -Path "monotools.zip" -DestinationPath "."
        Rename-Item -Path "MonoTools-master" -NewName "MonoTools"
        
        # Download GuiTools
        Invoke-WebRequest -Uri "https://github.com/rochus-keller/GuiTools/archive/refs/heads/master.zip" -OutFile "guitools.zip"
        Expand-Archive -Path "guitools.zip" -DestinationPath "."
        Rename-Item -Path "GuiTools-master" -NewName "GuiTools"
        
        # Download LeanQt
        Invoke-WebRequest -Uri "https://github.com/rochus-keller/LeanQt/archive/refs/heads/main.zip" -OutFile "leanqt.zip"
        Expand-Archive -Path "leanqt.zip" -DestinationPath "."
        Rename-Item -Path "LeanQt-main" -NewName "LeanQt"
      shell: powershell
      
    - name: Build ObxIDE
      run: |
        Set-Location BUSY
        .\lua.exe build.lua .. -T ide
      shell: powershell
      
    - name: Package artifacts
      run: |
        Set-Location BUSY\output
        New-Item -ItemType Directory -Path "..\..\artifacts" -Force
        
        if (Test-Path "ObxIDE.exe") {
          Copy-Item "ObxIDE.exe" "..\..\artifacts\ObxIDE_${{ matrix.output_suffix }}.exe"
        }
        
        if (Test-Path "mono") {
          Copy-Item "mono" "..\..\artifacts\" -Recurse
        }
        
        # Add build information
        "Build: ${{ github.sha }}" | Out-File "..\..\artifacts\build_info.txt"
        "Date: $(Get-Date)" | Out-File "..\..\artifacts\build_info.txt" -Append
        "Platform: ${{ matrix.output_suffix }}" | Out-File "..\..\artifacts\build_info.txt" -Append
      shell: powershell
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ObxIDE_${{ matrix.output_suffix }}
        path: artifacts/
        retention-days: 30

